#!/usr/bin/with-contenv bash
# shellcheck shell=bash

USER_NAME=${USER_NAME:-linuxserver.io}

PUID=${PUID:-911}
PGID=${PGID:-911}

if [[ "$USER_NAME" != "abc" ]]; then
    usermod -l "$USER_NAME" abc
    groupmod -n "$USER_NAME" abc
fi

groupmod -o -g "$PGID" "$USER_NAME"
usermod -o -u "$PUID" "$USER_NAME"

cat /etc/s6-overlay/s6-rc.d/init-adduser/branding

if [[ -f /donate.txt ]]; then
    echo '
To support the app dev(s) visit:'
    cat /donate.txt
fi
echo '
To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u "${USER_NAME}")
User GID:    $(id -g "${USER_NAME}")
───────────────────────────────────────
"

if [[ "$(uname -m)" == "armv7l" ]] || [[ "$(uname -m)" == "armhf" ]]; then
    echo '
╔═════════════════════════════════════════════════════╗
║                                                     ║
║      The 32-bit Arm version of this image will      ║
║       no longer be supported after 2023-07-01       ║
║                                                     ║
║          See: https://linuxserver.io/armhf          ║
║                  for more details                   ║
║                                                     ║
╚═════════════════════════════════════════════════════╝
'
fi

lsiown "${USER_NAME}":"${USER_NAME}" /app
lsiown "${USER_NAME}":"${USER_NAME}" /config
lsiown "${USER_NAME}":"${USER_NAME}" /defaults
