#!/usr/bin/with-contenv bash

USER_NAME=${USER_NAME:-linuxserver.io}

PUID=${PUID:-911}
PGID=${PGID:-911}

[[ "$USER_NAME" != "abc" ]] && \
    usermod -l "$USER_NAME" abc && \
    groupmod -n "$USER_NAME" abc

groupmod -o -g "$PGID" "$USER_NAME"
usermod -o -u "$PUID" "$USER_NAME"

echo '
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u "$USER_NAME")
User gid:    $(id -g "$USER_NAME")
-------------------------------------
"

time32="$(date +%Y)"

if [[ "${time32}" == "1970" || "${time32}" == "1969" ]] && [ "$(uname -m)" == "armv7l" ]; then
  echo '
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
'
fi

chown "$USER_NAME":"$USER_NAME" /app
chown "$USER_NAME":"$USER_NAME" /config
chown "$USER_NAME":"$USER_NAME" /defaults
