#!/usr/bin/with-contenv bash

USER_NAME=${USER_NAME:-linuxserver.io}
GROUP_NAME=${GROUP_NAME:-linuxserver.io}

PUID=${PUID:-911}
PGID=${PGID:-911}

if [ "$BAD_USER_NAME" == "true" ]; then
  [[ "$USER_NAME" != "abc" ]] && \
    usermod -b -l "$USER_NAME" abc && \
    groupmod -n "$GROUP_NAME" abc
else
  [[ "$USER_NAME" != "abc" ]] && \
    usermod -l "$USER_NAME" abc && \
    groupmod -n "$GROUP_NAME" abc
fi

groupmod -o -g "$PGID" "$GROUP_NAME"
usermod -o -u "$PUID" "$USER_NAME"

echo '
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u "$USER_NAME")
User gid:    $(id -g "$USER_NAME")
-------------------------------------
"
chown "$USER_NAME":"$GROUP_NAME" /app
chown "$USER_NAME":"$GROUP_NAME" /config
chown "$USER_NAME":"$GROUP_NAME" /defaults
