#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
    /config/.ssh

USER_NAME=${USER_NAME:-abc}

# set password for abc to unlock it and set sudo access
sed -i "/${USER_NAME} ALL.*/d" /etc/sudoers
if [ "$SUDO_ACCESS" == "true" ]; then
    if [ -n "$SUDO_PASSWORD" ]; then
        echo "${USER_NAME} ALL=(ALL) ALL" >> /etc/sudoers
    else
        echo "${USER_NAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    fi
fi
SUDO_PASSWORD=${SUDO_PASSWORD:-$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-8};echo;)}
echo "${USER_NAME}:${SUDO_PASSWORD}" | chpasswd

if [ ! -d /config/ssh_host_keys ];then
    cp -R /etc/ssh /config/ssh_host_keys
fi

if [ ! -f /config/.ssh/authorized_keys ];then
    touch /config/.ssh/authorized_keys
fi

[[ -n "$PUBLIC_KEY" ]] && \
    [[ ! $(grep "$PUBLIC_KEY" /config/.ssh/authorized_keys) ]] && \
    echo "$PUBLIC_KEY" >> /config/.ssh/authorized_keys

rm -rf /etc/ssh
cp -R /config/ssh_host_keys /etc/ssh

# permissions
chown -R "${USER_NAME}":"${USER_NAME}" \
    /config
chown -R root:root \
    /etc/ssh
chmod 700 \
    /config/.ssh
chmod 600 \
    /config/.ssh/authorized_keys